DROP DATABASE openCTF;
CREATE DATABASE openCTF;
USE openCTF;

CREATE TABLE Utente (
	username VARCHAR(50) NOT NULL,
	password VARCHAR(100) NOT NULL,
	data TIMESTAMP NOT NULL,
	PRIMARY KEY (username)
);

CREATE TABLE CTF (
	id INTEGER NOT NULL AUTO_INCREMENT,
	titolo VARCHAR(100) NOT NULL,
	difficolta INTEGER NOT NULL,
	CONSTRAINT difficolta CHECK (difficolta BETWEEN 1 AND 10),
	data TIMESTAMP NOT NULL,
	descrizione VARCHAR(500) NOT NULL,
	flag VARCHAR(100) NOT NULL,
	utente VARCHAR(50) NOT NULL,
	categoria ENUM("Binary Exploitation", "Web Exploitation", "Reverse Engineering", "Forensic") NOT NULL,
	PRIMARY KEY (id)
);
ALTER TABLE CTF
	ADD FOREIGN KEY (utente) REFERENCES Utente (username);

CREATE TABLE Files (
	nome VARCHAR(100) NOT NULL,
	ctf INTEGER NOT NULL,
	PRIMARY KEY (nome, ctf)
);
ALTER TABLE Files
	ADD FOREIGN KEY (ctf) REFERENCES CTF (id);

CREATE TABLE Commenti (
	id INTEGER NOT NULL AUTO_INCREMENT,
	ts TIMESTAMP NOT NULL,
	testo VARCHAR(1000) NOT NULL,
	utente VARCHAR(50) NOT NULL,
	ctf INTEGER NOT NULL,
	PRIMARY KEY (id)
);
ALTER TABLE Commenti
	ADD FOREIGN KEY (utente) REFERENCES Utente (username);
ALTER TABLE Commenti
	ADD FOREIGN KEY (ctf) REFERENCES CTF (id);

CREATE TABLE Indizi (
	id INTEGER NOT NULL AUTO_INCREMENT,
	testo VARCHAR(1000) NOT NULL,
	ctf INTEGER NOT NULL,
	PRIMARY KEY (id)
);
ALTER TABLE Indizi
	ADD FOREIGN KEY (ctf) REFERENCES CTF (id);

CREATE TABLE Prova (
	utente VARCHAR(50) NOT NULL,
	ctf INTEGER NOT NULL,
	PRIMARY KEY (utente, ctf)
);
ALTER TABLE Prova
	ADD FOREIGN KEY (utente) REFERENCES Utente (username);
ALTER TABLE Prova
	ADD FOREIGN KEY (ctf) REFERENCES CTF (id);

CREATE TABLE Writeup (
	nome VARCHAR(100) NOT NULL,
	utente VARCHAR(50) NOT NULL,
	ctf INTEGER NOT NULl,
	ts TIMESTAMP NOT NULL,
	PRIMARY KEY (utente, ctf)
);
ALTER TABLE Writeup
	ADD FOREIGN KEY (utente) REFERENCES Utente (username);
ALTER TABLE Writeup
	ADD FOREIGN KEY (ctf) REFERENCES CTF (id);

CREATE TABLE Risolte (
	utente VARCHAR(50) NOT NULL,
	ctf INTEGER NOT NULl,
	ts TIMESTAMP NOT NULL,
	PRIMARY KEY (utente, ctf)
);
ALTER TABLE Risolte
	ADD FOREIGN KEY (utente) REFERENCES Utente (username);
ALTER TABLE Risolte
	ADD FOREIGN KEY (ctf) REFERENCES CTF (id);